# Learn & Understand PyTorch

In [1]:
print("Helllo, I'm excited to learn Pytorch")

Helllo, I'm excited to learn Pytorch


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.11.0+cpu


# Introduction to tensor

## Creating tensors

Tensor is a multi-dimensional matrix containing elements of a single data type

In [4]:
# scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
# Vector

vector = torch.tensor([2, 4, 5])

print(vector)
print(vector.ndim)
print(vector.shape)

tensor([2, 4, 5])
1
torch.Size([3])


In [8]:
# Matrix
MATRIX = torch.tensor([[1., -1.], [2., -5.]])
MATRIX

tensor([[ 1., -1.],
        [ 2., -5.]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX.item()

RuntimeError: a Tensor with 4 elements cannot be converted to Scalar

In [12]:
MATRIX[1]

tensor([ 2., -5.])

In [13]:
# Tensor

Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [16]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [35]:
Tensor[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [36]:
Tensor2 = torch.tensor([[2, 3, 5],
                        [4, 6, 8]])

Tensor2.shape

torch.Size([2, 3])

In [37]:
Tensor2.ndim

2

---

### Random Tensors


Random Tensors are important cuz many neural networks learn is that they start with tensors full of random values and they adjust those random numbers to better represent data.

In [38]:
# Create random tensor with size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4168, 0.0333, 0.5027, 0.6152],
        [0.8562, 0.2520, 0.5742, 0.7100],
        [0.2463, 0.9010, 0.2295, 0.7216]])

In [39]:
# with similar shape to an image tensor

random_img_size_tensor = torch.rand(size=(224,224, 3))
random_img_size_tensor

random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [40]:
# Zeros and Ones

zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [42]:
ones.dtype

torch.float32

In [43]:
random_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [44]:
# torch.range()

one_to_ten = torch.arange(1, 11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**NOTE** : Tensor datatype က one of 3 big error in PyTorch.

1. Tensors not right dtype
2. Tensors not right shape
3. Tensors not on right device

In [46]:
Tensor3 = torch.tensor([3.0, 4.0, 9.0],
                       dtype=torch.float16,
                       device=None, # which device is your tensor on
                       requires_grad=False) # whether or not to track gradients

Tensor3.dtype

torch.float16

In [47]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)

int_32_tensor

tensor([3, 6, 9])

In [48]:
Tensor3 * int_32_tensor

tensor([ 9., 24., 81.], dtype=torch.float16)

## Getting info from tensors

In [49]:
rand_tensor = torch.rand(3,4)

print(rand_tensor)
print(f"\nShape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is on: {rand_tensor.device}")

tensor([[0.4094, 0.4362, 0.2639, 0.7573],
        [0.0774, 0.3737, 0.7325, 0.9620],
        [0.6126, 0.8387, 0.9082, 0.1843]])

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:


* Addition
*   Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication



In [50]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [51]:
tensor * 10

tensor([10, 20, 30])

In [52]:
tensor - 3

tensor([-2, -1,  0])

In [53]:
tensor = torch.tensor([10, 20, 30])

tensor / 2

tensor([ 5., 10., 15.])

In [54]:
# Try Pytorch built-in function

torch.mul(tensor, 10)

tensor([100, 200, 300])

Matrix Multiplication (dot product)

In [55]:
tensor = torch.tensor([1,2,3])

# Element-wise multiplication

print(tensor, "*", tensor)
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [56]:
# Matrix Multiplication

print(torch.matmul(tensor, tensor))

tensor(14)


Transpose

In [57]:
tensorA = torch.rand(2, 3)
tensorA

tensor([[0.3509, 0.7150, 0.1726],
        [0.4139, 0.5983, 0.5560]])

In [58]:
tensorB = torch.rand(2, 3)
tensorB

tensor([[0.0687, 0.3845, 0.6749],
        [0.5030, 0.7402, 0.5378]])

In [60]:
torch.matmul(tensorA, tensorB)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [61]:
tensorB.T

tensor([[0.0687, 0.5030],
        [0.3845, 0.7402],
        [0.6749, 0.5378]])

In [62]:
tensorB

tensor([[0.0687, 0.3845, 0.6749],
        [0.5030, 0.7402, 0.5378]])

In [63]:
torch.matmul(tensorA, tensorB.T)

tensor([[0.4155, 0.7986],
        [0.6337, 0.9501]])

## Find min, max, mean, sum, etc (tensor aggregation)

In [64]:
x = torch.arange(20, 100, 10)
x

tensor([20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
x.dtype

torch.int64

In [66]:
# Find the min
torch.min(x)

tensor(20)

In [67]:
# Find the max
torch.max(x)

tensor(90)

In [68]:
# mean
torch.mean(x.type(torch.float32))

tensor(55.)

In [69]:
# sum
torch.sum(x)

tensor(440)

---

## Finding the postional min and max

In [70]:
x

tensor([20, 30, 40, 50, 60, 70, 80, 90])

In [71]:
# return index value of min value

x.argmin()

tensor(0)

In [72]:
# positon of max value

x.argmax()

tensor(7)

---

## Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping : reshapes an input tensor to a defined shape
- Viewing : Return a view of an input tensor of certain shape but keep the same memory as the orignal tensor
- Stacking : combine multiple tensors on top of eah other (vstack) or side by side (hstack)

- Squeeze : remove all `1` dimensions from a tensor
- Unsqueeze : add a `1` dimension to a target tensor

- Permute : return a view of the input with dimensions permuted (swapped) in a certain way

In [73]:
import torch
x = torch.arange(1, 11, 1)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [77]:
# add extra dim

x_reshaped = x.reshape(5, 2) # 10, 1
x_reshaped

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [78]:
# Change the view

z = x.view(1, 10)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

If we change z in this view function, the original value x is also changed.

In [79]:
z[:, 0] = 5
x

tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
# Stack tensors on top of each other

x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

When dim is given, a squeeze operation is done only in the given dimension(s). If input is of shape:
(
A
×
1
×
B
)
(A×1×B)
, squeeze(input, 0) leaves the tensor unchanged, but squeeze(input, 1) will squeeze the tensor to the shape
(
A
×
B
)
(A×B)
.

In [93]:
# Squeeze

x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [94]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [95]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [96]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [99]:
x_reshaped.size()

torch.Size([5, 2])

In [115]:
y = torch.arange(10, 50, 5)
print(f"\nPrevious tensor: {y}")
print(f"Previous shape: {y.size()}\n")

y = y.reshape(1, 8)
print(f"New tensor : {y}")
print(f"New shape: {y.size()}")

print(f"\nAfter squeezing...")
y_squeezed = torch.squeeze(y)

print(f"Updated shape: {y_squeezed.size()}")


Previous tensor: tensor([10, 15, 20, 25, 30, 35, 40, 45])
Previous shape: torch.Size([8])

New tensor : tensor([[10, 15, 20, 25, 30, 35, 40, 45]])
New shape: torch.Size([1, 8])

After squeezing...
Updated shape: torch.Size([8])


In [118]:
# Unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=1)

print(f"Before unsqueezing...\nPrevious target: {y_squeezed.size()}\n\nAfter unsqueezing...\nNew Shape: {y_unsqueezed.size()} ")

Before unsqueezing...
Previous target: torch.Size([8])

After unsqueezing...
New Shape: torch.Size([8, 1]) 


In [119]:
# Permute - rearrange the dimensions of a target tensor in a specified order

x_org = torch.rand(224, 224, 3)
x_permuted = x_org.permute(2, 0, 1)

print(f"Original tensor shape: {x_org.size()}\n\nAfter permuting...\nNew Tensor shape: {x_permuted.size()}")

Original tensor shape: torch.Size([224, 224, 3])

After permuting...
New Tensor shape: torch.Size([3, 224, 224])


In [120]:
x_org

tensor([[[0.3934, 0.3361, 0.6853],
         [0.0065, 0.5062, 0.4319],
         [0.0655, 0.0793, 0.5999],
         ...,
         [0.5212, 0.6976, 0.3617],
         [0.5707, 0.1295, 0.8632],
         [0.5285, 0.6435, 0.4017]],

        [[0.0989, 0.1122, 0.4469],
         [0.2972, 0.0106, 0.3645],
         [0.8080, 0.5589, 0.4289],
         ...,
         [0.6197, 0.3105, 0.3361],
         [0.4354, 0.9427, 0.0656],
         [0.3272, 0.0971, 0.7793]],

        [[0.4246, 0.9041, 0.3220],
         [0.2093, 0.7366, 0.9090],
         [0.7152, 0.7416, 0.3420],
         ...,
         [0.1378, 0.7965, 0.7960],
         [0.5782, 0.7763, 0.4809],
         [0.4544, 0.3380, 0.0940]],

        ...,

        [[0.1489, 0.4805, 0.5773],
         [0.2751, 0.1311, 0.7289],
         [0.0659, 0.9149, 0.2479],
         ...,
         [0.3558, 0.6374, 0.1359],
         [0.0143, 0.2925, 0.7785],
         [0.3164, 0.6028, 0.7277]],

        [[0.2904, 0.8558, 0.5106],
         [0.6277, 0.9778, 0.0898],
         [0.

Like view( )...

In [123]:
x_org[0, 0, 0] = 0.49

print(x_org[0,0,0])
print(x_permuted[0,0,0])

tensor(0.4900)
tensor(0.4900)


## Indexing (Select data from Tensors)

In [124]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [125]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [126]:
x[0][0]

tensor([1, 2, 3])

In [127]:
x[0][1]

tensor([4, 5, 6])

Challenge (in-class)

In [128]:
x[0][2][2]

tensor(9)

**Select `:` to select "all" of a target dimension**

In [129]:
x[:,0]

tensor([[1, 2, 3]])

In [131]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [132]:
x[:, 1, 1]

tensor([5])

In [133]:
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch & NumPy

In [134]:
# NumPy array to Tensor

import torch
import numpy as np

array = np.arange(1, 8)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [135]:
tensor.dtype

torch.int64

In [136]:
array = array + 1

array, tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [137]:
# Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [138]:
numpy_tensor.dtype

dtype('float32')

In [140]:
tensor = tensor + 1

tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take the random out ot random)

In [143]:
import torch

random_A = torch.rand(3, 4)
random_B = torch.rand(3, 4)

print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.2226, 0.8685, 0.8536, 0.3556],
        [0.3597, 0.7124, 0.2288, 0.4102],
        [0.5244, 0.5760, 0.6762, 0.3118]])
tensor([[0.0672, 0.5593, 0.0017, 0.6549],
        [0.0526, 0.4127, 0.9472, 0.7468],
        [0.8137, 0.8221, 0.4615, 0.9441]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [145]:
# make random but reproducible tensors

import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3, 4)

print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Accessing GPU

In [1]:
!nvidia-smi

Mon Jun 22 17:14:50 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
### Check for GPU access with PyTorch

import torch

torch.cuda.is_available()

True

## Setting up device agnostic code

In [4]:
# Setup device agnostic code

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [5]:
# Count the number of device
torch.cuda.device_count()

1

## Putting tensors (and models) on GPU

In [6]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Moving tensors back to CPU

In [8]:
tensor_backon_cpu = tensor_on_gpu.cpu().numpy()
tensor_backon_cpu

array([1, 2, 3])

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

---