# **The Beginning of My Tensorflow journey**

- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & NumPy
- Using @tf.function (a way to speed up your regular Python functions)
- Using GPUs with TensorFlow (or TPUs)

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [2]:
# create tensors with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scaler.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [9]:
# create matrix (has more than 1 dim)
matrix = tf.constant([[10, 7],[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [17]:
another_matrix = tf.constant([[2, 3], [4,5], [3, 6]])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [3, 6]], dtype=int32)>

In [18]:
another_matrix.ndim

2

In [19]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [20]:
tensor.ndim

3

What we've created so far:

Scalar: a single number
Vector: a number with direction (e.g. wind speed and direction)
Matrix: a 2-dimensional array of numbers
Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# Creating tensors with **tf.Variable**

In [24]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [25]:
changable_tensor[0] = 7
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [26]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [27]:
# for unchangable tensor
unchangable_tensor[0].assing(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assing'

🔑 Note: Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

### **Creating random tensors**

Random tensors are tensors of some arbitrary size which contain random numbers.

In [36]:
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3, 2))
random_1

random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.2878567 ],
       [-0.87579006, -0.08857017],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [37]:
# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.87579006, -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.87579006, -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [47]:
# shuffle tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)

not_shuffled = tf.constant([[10, 7],
                      [3, 4],
                       [2, 5]])
# shuffle this
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [51]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=9)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [54]:
ts1 = tf.random.Generator.from_seed(9)
ts1 = tf.random.normal(shape=[2, 3])
ts1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479]], dtype=float32)>

In [60]:
tf.random.set_seed(42)
tf.random.shuffle(ts1, seed=7)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479]], dtype=float32)>

In [62]:
tf2=tf.random.Generator.from_seed(7)
tf2 = tf.random.normal(shape=[2,2])

print(tf2)

tf.random.set_seed(7)
print(tf.random.shuffle(tf2, seed=9))

tf.Tensor(
[[ 0.3274685 -0.8426258]
 [ 0.3194337 -1.4075519]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.3194337 -1.4075519]
 [ 0.3274685 -0.8426258]], shape=(2, 2), dtype=float32)


In [64]:
tensor = tf.random.Generator.from_seed(9)
tensor = tf.random.normal(shape=[3, 4])

print(tensor)

tf.random.set_seed(8)
print(tf.random.shuffle(tensor, seed=2))


tf.Tensor(
[[ 0.3274685  -0.8426258   0.3194337  -1.4075519 ]
 [-2.3880599  -1.0392479  -0.5573232   0.539707  ]
 [ 1.6994323   0.28893656 -1.5066116  -0.2645474 ]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 1.6994323   0.28893656 -1.5066116  -0.2645474 ]
 [-2.3880599  -1.0392479  -0.5573232   0.539707  ]
 [ 0.3274685  -0.8426258   0.3194337  -1.4075519 ]], shape=(3, 4), dtype=float32)


# Other ways to make tensors

In [70]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [71]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn NumPy arrays into tensors


The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [76]:
# You can also turn NumPy arrays into tensors

import numpy as np
np_A = np.arange(1, 25, dtype=np.int32)
np_A.ndim

1

In [77]:
A = tf.constant(np_A, shape=(3, 8))
B = tf.constant(np_A)

A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [78]:
3 * 8

24

In [81]:
C = tf.constant(np_A, shape=(2, 12))
C

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [82]:
A.ndim

2

In [83]:
B.ndim

1

# Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:

Shape  
Rank    
Axis or dimension   
Size

In [85]:
# create rank 4 tensor (4D)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [87]:
print(rank_4_tensor.shape)
print('\n')

print(rank_4_tensor.ndim)
print('\n')

print(tf.size(rank_4_tensor))

(2, 3, 4, 5)


4


tf.Tensor(120, shape=(), dtype=int32)


In [88]:
2 * 3 * 4 * 5

120

# Various attributes of our tensor

In [89]:
print('Datatype of every elements : ', rank_4_tensor.dtype)
print(f'Number of dimensions (rank) : {rank_4_tensor.ndim}')
print('Shape of tensor : ', rank_4_tensor.shape)
print('Elemeents along the 0 axis: ', rank_4_tensor.shape[0])

Datatype of every elements :  <dtype: 'float32'>
Number of dimensions (rank) : 4
Shape of tensor :  (2, 3, 4, 5)
Elemeents along the 0 axis:  2


In [90]:
print('Elements along the last axis : ', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor: ', tf.size(rank_4_tensor))
print('Total number of elements in our tensor : ', tf.size(rank_4_tensor).numpy())

Elements along the last axis :  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor :  120


### Indexing tensors